# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemple.mp3"
Content-Type: audio/mpeg

< ./test.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/89d5cdaa-93c3-489e-9be1-e215945fa664/transcription
Content-Type: application/json

{
  "prompt": "ESLint, Prettier, Tailwind"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "89d5cdaa-93c3-489e-9be1-e215945fa664",
  "template": "Gere um resumo suncito da transcrioção do vídeo informada a seguir: '''{transcription}'''",
  "temperature": 0.5
}